server:
  port: 8086
spring:
  redis:
    port: 6379
    host: 134.175.206.167
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    database: 0
