server:
  port: 8086
spring:
  rabbitmq:
    host: 39.108.146.20
    port: 5672
    username: sueno
    password: sueno
    virtual-host: mbql
    publisher-confirms: true
    publisher-returns: true

