server:
  port: 8081
  servlet:
    context-path: /api-front
spring:
  redis:
    database: 0
    host: 134.175.206.167
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        maxActive: 10
